### ISSUE TITLE
Please upgrade packages

### ISSUE THREAD

**Issue by dylanh724** [executablebooks/rst-to-myst#78]
### Context

Using Sphinx 8 requires a ton of different packages, all which are not really compatible with myst2rst. Eg:

```
rst-to-myst 0.4.0 requires docutils<0.20,>=0.17, but you have docutils 0.21.2 which is incompatible.

rst-to-myst 0.4.0 requires markdown-it-py~=2.0, but you have markdown-it-py 3.0.0 which is incompatible.

rst-to-myst 0.4.0 requires mdformat-myst~=0.1.5, but you have mdformat-myst 0.2.1 which is incompatible.
```

### Proposal

Please update packages -> ensure compat -> open compat ver range

### Tasks and updates

- [ ] Update packages to support Sphinx 8
- [ ] Test to ensure compatibility
- [ ] Open compatibility version range

Related (would combo fix): https://github.com/executablebooks/rst-to-myst/issues/77
